version: '3.8'
services:
  app2:
    image: nginx:alpine
    container_name: azer
    restart: unless-stopped
    ports:
      - '127.0.0.1:6900:80'
    networks:
      - proxy-network
    volumes:
      - ./:/usr/share/nginx/html:ro

networks:
  proxy-network:
    external: true